# Generated by Django 3.2 on 2021-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_img', models.ImageField(upload_to='pics')),
                ('post_con', models.CharField(max_length=300)),
                ('post_author', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField()),
                ('post_comment_count', models.IntegerField()),
                ('post_tag', models.CharField(max_length=30)),
            ],
        ),
    ]
