# Generated by Django 3.2 on 2021-12-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
            ],
        ),
    ]
